#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_akhir
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="distroshop")]
	public partial class distroshopDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdetailpembelian(detailpembelian instance);
    partial void Updatedetailpembelian(detailpembelian instance);
    partial void Deletedetailpembelian(detailpembelian instance);
    partial void Insertdetailpesanan(detailpesanan instance);
    partial void Updatedetailpesanan(detailpesanan instance);
    partial void Deletedetailpesanan(detailpesanan instance);
    partial void Insertkategori(kategori instance);
    partial void Updatekategori(kategori instance);
    partial void Deletekategori(kategori instance);
    partial void Insertpelanggan(pelanggan instance);
    partial void Updatepelanggan(pelanggan instance);
    partial void Deletepelanggan(pelanggan instance);
    partial void Insertpemasok(pemasok instance);
    partial void Updatepemasok(pemasok instance);
    partial void Deletepemasok(pemasok instance);
    partial void Insertpembelian(pembelian instance);
    partial void Updatepembelian(pembelian instance);
    partial void Deletepembelian(pembelian instance);
    partial void Insertpengguna(pengguna instance);
    partial void Updatepengguna(pengguna instance);
    partial void Deletepengguna(pengguna instance);
    partial void Insertpesanan(pesanan instance);
    partial void Updatepesanan(pesanan instance);
    partial void Deletepesanan(pesanan instance);
    partial void Insertproduk(produk instance);
    partial void Updateproduk(produk instance);
    partial void Deleteproduk(produk instance);
    partial void Insertvarianproduk(varianproduk instance);
    partial void Updatevarianproduk(varianproduk instance);
    partial void Deletevarianproduk(varianproduk instance);
    #endregion
		
		public distroshopDataContext() : 
				base(global::Project_akhir.Properties.Settings.Default.distroshopConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public distroshopDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public distroshopDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public distroshopDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public distroshopDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<detailpembelian> detailpembelians
		{
			get
			{
				return this.GetTable<detailpembelian>();
			}
		}
		
		public System.Data.Linq.Table<detailpesanan> detailpesanans
		{
			get
			{
				return this.GetTable<detailpesanan>();
			}
		}
		
		public System.Data.Linq.Table<kategori> kategoris
		{
			get
			{
				return this.GetTable<kategori>();
			}
		}
		
		public System.Data.Linq.Table<pelanggan> pelanggans
		{
			get
			{
				return this.GetTable<pelanggan>();
			}
		}
		
		public System.Data.Linq.Table<pemasok> pemasoks
		{
			get
			{
				return this.GetTable<pemasok>();
			}
		}
		
		public System.Data.Linq.Table<pembelian> pembelians
		{
			get
			{
				return this.GetTable<pembelian>();
			}
		}
		
		public System.Data.Linq.Table<pengguna> penggunas
		{
			get
			{
				return this.GetTable<pengguna>();
			}
		}
		
		public System.Data.Linq.Table<pesanan> pesanans
		{
			get
			{
				return this.GetTable<pesanan>();
			}
		}
		
		public System.Data.Linq.Table<produk> produks
		{
			get
			{
				return this.GetTable<produk>();
			}
		}
		
		public System.Data.Linq.Table<varianproduk> varianproduks
		{
			get
			{
				return this.GetTable<varianproduk>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detailpembelian")]
	public partial class detailpembelian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdPembelian;
		
		private int _IdVarian;
		
		private System.Nullable<int> _Jumlah;
		
		private System.Nullable<decimal> _HargaBeli;
		
		private System.Nullable<decimal> _SubTotal;
		
		private EntityRef<pembelian> _pembelian;
		
		private EntityRef<varianproduk> _varianproduk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdPembelianChanging(int value);
    partial void OnIdPembelianChanged();
    partial void OnIdVarianChanging(int value);
    partial void OnIdVarianChanged();
    partial void OnJumlahChanging(System.Nullable<int> value);
    partial void OnJumlahChanged();
    partial void OnHargaBeliChanging(System.Nullable<decimal> value);
    partial void OnHargaBeliChanged();
    partial void OnSubTotalChanging(System.Nullable<decimal> value);
    partial void OnSubTotalChanged();
    #endregion
		
		public detailpembelian()
		{
			this._pembelian = default(EntityRef<pembelian>);
			this._varianproduk = default(EntityRef<varianproduk>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPembelian", DbType="Int NOT NULL")]
		public int IdPembelian
		{
			get
			{
				return this._IdPembelian;
			}
			set
			{
				if ((this._IdPembelian != value))
				{
					if (this._pembelian.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPembelianChanging(value);
					this.SendPropertyChanging();
					this._IdPembelian = value;
					this.SendPropertyChanged("IdPembelian");
					this.OnIdPembelianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVarian", DbType="Int NOT NULL")]
		public int IdVarian
		{
			get
			{
				return this._IdVarian;
			}
			set
			{
				if ((this._IdVarian != value))
				{
					if (this._varianproduk.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdVarianChanging(value);
					this.SendPropertyChanging();
					this._IdVarian = value;
					this.SendPropertyChanged("IdVarian");
					this.OnIdVarianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah", DbType="Int")]
		public System.Nullable<int> Jumlah
		{
			get
			{
				return this._Jumlah;
			}
			set
			{
				if ((this._Jumlah != value))
				{
					this.OnJumlahChanging(value);
					this.SendPropertyChanging();
					this._Jumlah = value;
					this.SendPropertyChanged("Jumlah");
					this.OnJumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaBeli", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> HargaBeli
		{
			get
			{
				return this._HargaBeli;
			}
			set
			{
				if ((this._HargaBeli != value))
				{
					this.OnHargaBeliChanging(value);
					this.SendPropertyChanging();
					this._HargaBeli = value;
					this.SendPropertyChanged("HargaBeli");
					this.OnHargaBeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SubTotal
		{
			get
			{
				return this._SubTotal;
			}
			set
			{
				if ((this._SubTotal != value))
				{
					this.OnSubTotalChanging(value);
					this.SendPropertyChanging();
					this._SubTotal = value;
					this.SendPropertyChanged("SubTotal");
					this.OnSubTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pembelian_detailpembelian", Storage="_pembelian", ThisKey="IdPembelian", OtherKey="IdPembelian", IsForeignKey=true)]
		public pembelian pembelian
		{
			get
			{
				return this._pembelian.Entity;
			}
			set
			{
				pembelian previousValue = this._pembelian.Entity;
				if (((previousValue != value) 
							|| (this._pembelian.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pembelian.Entity = null;
						previousValue.detailpembelians.Remove(this);
					}
					this._pembelian.Entity = value;
					if ((value != null))
					{
						value.detailpembelians.Add(this);
						this._IdPembelian = value.IdPembelian;
					}
					else
					{
						this._IdPembelian = default(int);
					}
					this.SendPropertyChanged("pembelian");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="varianproduk_detailpembelian", Storage="_varianproduk", ThisKey="IdVarian", OtherKey="IdVarian", IsForeignKey=true)]
		public varianproduk varianproduk
		{
			get
			{
				return this._varianproduk.Entity;
			}
			set
			{
				varianproduk previousValue = this._varianproduk.Entity;
				if (((previousValue != value) 
							|| (this._varianproduk.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._varianproduk.Entity = null;
						previousValue.detailpembelians.Remove(this);
					}
					this._varianproduk.Entity = value;
					if ((value != null))
					{
						value.detailpembelians.Add(this);
						this._IdVarian = value.IdVarian;
					}
					else
					{
						this._IdVarian = default(int);
					}
					this.SendPropertyChanged("varianproduk");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detailpesanan")]
	public partial class detailpesanan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdPesanan;
		
		private int _IdVarian;
		
		private System.Nullable<int> _Jumlah;
		
		private System.Nullable<decimal> _HargaSatuan;
		
		private System.Nullable<decimal> _SubTotal;
		
		private EntityRef<pesanan> _pesanan;
		
		private EntityRef<varianproduk> _varianproduk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdPesananChanging(int value);
    partial void OnIdPesananChanged();
    partial void OnIdVarianChanging(int value);
    partial void OnIdVarianChanged();
    partial void OnJumlahChanging(System.Nullable<int> value);
    partial void OnJumlahChanged();
    partial void OnHargaSatuanChanging(System.Nullable<decimal> value);
    partial void OnHargaSatuanChanged();
    partial void OnSubTotalChanging(System.Nullable<decimal> value);
    partial void OnSubTotalChanged();
    #endregion
		
		public detailpesanan()
		{
			this._pesanan = default(EntityRef<pesanan>);
			this._varianproduk = default(EntityRef<varianproduk>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPesanan", DbType="Int NOT NULL")]
		public int IdPesanan
		{
			get
			{
				return this._IdPesanan;
			}
			set
			{
				if ((this._IdPesanan != value))
				{
					if (this._pesanan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPesananChanging(value);
					this.SendPropertyChanging();
					this._IdPesanan = value;
					this.SendPropertyChanged("IdPesanan");
					this.OnIdPesananChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVarian", DbType="Int NOT NULL")]
		public int IdVarian
		{
			get
			{
				return this._IdVarian;
			}
			set
			{
				if ((this._IdVarian != value))
				{
					if (this._varianproduk.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdVarianChanging(value);
					this.SendPropertyChanging();
					this._IdVarian = value;
					this.SendPropertyChanged("IdVarian");
					this.OnIdVarianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah", DbType="Int")]
		public System.Nullable<int> Jumlah
		{
			get
			{
				return this._Jumlah;
			}
			set
			{
				if ((this._Jumlah != value))
				{
					this.OnJumlahChanging(value);
					this.SendPropertyChanging();
					this._Jumlah = value;
					this.SendPropertyChanged("Jumlah");
					this.OnJumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaSatuan", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> HargaSatuan
		{
			get
			{
				return this._HargaSatuan;
			}
			set
			{
				if ((this._HargaSatuan != value))
				{
					this.OnHargaSatuanChanging(value);
					this.SendPropertyChanging();
					this._HargaSatuan = value;
					this.SendPropertyChanged("HargaSatuan");
					this.OnHargaSatuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SubTotal
		{
			get
			{
				return this._SubTotal;
			}
			set
			{
				if ((this._SubTotal != value))
				{
					this.OnSubTotalChanging(value);
					this.SendPropertyChanging();
					this._SubTotal = value;
					this.SendPropertyChanged("SubTotal");
					this.OnSubTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pesanan_detailpesanan", Storage="_pesanan", ThisKey="IdPesanan", OtherKey="IdPesanan", IsForeignKey=true)]
		public pesanan pesanan
		{
			get
			{
				return this._pesanan.Entity;
			}
			set
			{
				pesanan previousValue = this._pesanan.Entity;
				if (((previousValue != value) 
							|| (this._pesanan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pesanan.Entity = null;
						previousValue.detailpesanans.Remove(this);
					}
					this._pesanan.Entity = value;
					if ((value != null))
					{
						value.detailpesanans.Add(this);
						this._IdPesanan = value.IdPesanan;
					}
					else
					{
						this._IdPesanan = default(int);
					}
					this.SendPropertyChanged("pesanan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="varianproduk_detailpesanan", Storage="_varianproduk", ThisKey="IdVarian", OtherKey="IdVarian", IsForeignKey=true)]
		public varianproduk varianproduk
		{
			get
			{
				return this._varianproduk.Entity;
			}
			set
			{
				varianproduk previousValue = this._varianproduk.Entity;
				if (((previousValue != value) 
							|| (this._varianproduk.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._varianproduk.Entity = null;
						previousValue.detailpesanans.Remove(this);
					}
					this._varianproduk.Entity = value;
					if ((value != null))
					{
						value.detailpesanans.Add(this);
						this._IdVarian = value.IdVarian;
					}
					else
					{
						this._IdVarian = default(int);
					}
					this.SendPropertyChanged("varianproduk");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kategori")]
	public partial class kategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKategori;
		
		private string _NamaKategori;
		
		private EntitySet<produk> _produks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKategoriChanging(int value);
    partial void OnIdKategoriChanged();
    partial void OnNamaKategoriChanging(string value);
    partial void OnNamaKategoriChanged();
    #endregion
		
		public kategori()
		{
			this._produks = new EntitySet<produk>(new Action<produk>(this.attach_produks), new Action<produk>(this.detach_produks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKategori", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdKategori
		{
			get
			{
				return this._IdKategori;
			}
			set
			{
				if ((this._IdKategori != value))
				{
					this.OnIdKategoriChanging(value);
					this.SendPropertyChanging();
					this._IdKategori = value;
					this.SendPropertyChanged("IdKategori");
					this.OnIdKategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaKategori", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NamaKategori
		{
			get
			{
				return this._NamaKategori;
			}
			set
			{
				if ((this._NamaKategori != value))
				{
					this.OnNamaKategoriChanging(value);
					this.SendPropertyChanging();
					this._NamaKategori = value;
					this.SendPropertyChanged("NamaKategori");
					this.OnNamaKategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategori_produk", Storage="_produks", ThisKey="IdKategori", OtherKey="IdKategori")]
		public EntitySet<produk> produks
		{
			get
			{
				return this._produks;
			}
			set
			{
				this._produks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_produks(produk entity)
		{
			this.SendPropertyChanging();
			entity.kategori = this;
		}
		
		private void detach_produks(produk entity)
		{
			this.SendPropertyChanging();
			entity.kategori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pelanggan")]
	public partial class pelanggan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPelanggan;
		
		private string _Nama;
		
		private string _JenisPelanggan;
		
		private string _Email;
		
		private string _NoTelepon;
		
		private string _Alamat;
		
		private System.Nullable<System.DateTime> _TanggalDaftar;
		
		private EntitySet<pesanan> _pesanans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPelangganChanging(int value);
    partial void OnIdPelangganChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnJenisPelangganChanging(string value);
    partial void OnJenisPelangganChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNoTeleponChanging(string value);
    partial void OnNoTeleponChanged();
    partial void OnAlamatChanging(string value);
    partial void OnAlamatChanged();
    partial void OnTanggalDaftarChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggalDaftarChanged();
    #endregion
		
		public pelanggan()
		{
			this._pesanans = new EntitySet<pesanan>(new Action<pesanan>(this.attach_pesanans), new Action<pesanan>(this.detach_pesanans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPelanggan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPelanggan
		{
			get
			{
				return this._IdPelanggan;
			}
			set
			{
				if ((this._IdPelanggan != value))
				{
					this.OnIdPelangganChanging(value);
					this.SendPropertyChanging();
					this._IdPelanggan = value;
					this.SendPropertyChanged("IdPelanggan");
					this.OnIdPelangganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JenisPelanggan", DbType="VarChar(50)")]
		public string JenisPelanggan
		{
			get
			{
				return this._JenisPelanggan;
			}
			set
			{
				if ((this._JenisPelanggan != value))
				{
					this.OnJenisPelangganChanging(value);
					this.SendPropertyChanging();
					this._JenisPelanggan = value;
					this.SendPropertyChanged("JenisPelanggan");
					this.OnJenisPelangganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoTelepon", DbType="VarChar(20)")]
		public string NoTelepon
		{
			get
			{
				return this._NoTelepon;
			}
			set
			{
				if ((this._NoTelepon != value))
				{
					this.OnNoTeleponChanging(value);
					this.SendPropertyChanging();
					this._NoTelepon = value;
					this.SendPropertyChanged("NoTelepon");
					this.OnNoTeleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat", DbType="VarChar(255)")]
		public string Alamat
		{
			get
			{
				return this._Alamat;
			}
			set
			{
				if ((this._Alamat != value))
				{
					this.OnAlamatChanging(value);
					this.SendPropertyChanging();
					this._Alamat = value;
					this.SendPropertyChanged("Alamat");
					this.OnAlamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalDaftar", DbType="Date")]
		public System.Nullable<System.DateTime> TanggalDaftar
		{
			get
			{
				return this._TanggalDaftar;
			}
			set
			{
				if ((this._TanggalDaftar != value))
				{
					this.OnTanggalDaftarChanging(value);
					this.SendPropertyChanging();
					this._TanggalDaftar = value;
					this.SendPropertyChanged("TanggalDaftar");
					this.OnTanggalDaftarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pelanggan_pesanan", Storage="_pesanans", ThisKey="IdPelanggan", OtherKey="IdPelanggan")]
		public EntitySet<pesanan> pesanans
		{
			get
			{
				return this._pesanans;
			}
			set
			{
				this._pesanans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pesanans(pesanan entity)
		{
			this.SendPropertyChanging();
			entity.pelanggan = this;
		}
		
		private void detach_pesanans(pesanan entity)
		{
			this.SendPropertyChanging();
			entity.pelanggan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pemasok")]
	public partial class pemasok : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPemasok;
		
		private string _Nama;
		
		private string _NoTelepon;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Tanggal;
		
		private string _Alamat;
		
		private string _Keterangan;
		
		private EntitySet<pembelian> _pembelians;
		
		private EntitySet<produk> _produks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPemasokChanging(int value);
    partial void OnIdPemasokChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnNoTeleponChanging(string value);
    partial void OnNoTeleponChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTanggalChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggalChanged();
    partial void OnAlamatChanging(string value);
    partial void OnAlamatChanged();
    partial void OnKeteranganChanging(string value);
    partial void OnKeteranganChanged();
    #endregion
		
		public pemasok()
		{
			this._pembelians = new EntitySet<pembelian>(new Action<pembelian>(this.attach_pembelians), new Action<pembelian>(this.detach_pembelians));
			this._produks = new EntitySet<produk>(new Action<produk>(this.attach_produks), new Action<produk>(this.detach_produks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPemasok", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPemasok
		{
			get
			{
				return this._IdPemasok;
			}
			set
			{
				if ((this._IdPemasok != value))
				{
					this.OnIdPemasokChanging(value);
					this.SendPropertyChanging();
					this._IdPemasok = value;
					this.SendPropertyChanged("IdPemasok");
					this.OnIdPemasokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoTelepon", DbType="VarChar(20)")]
		public string NoTelepon
		{
			get
			{
				return this._NoTelepon;
			}
			set
			{
				if ((this._NoTelepon != value))
				{
					this.OnNoTeleponChanging(value);
					this.SendPropertyChanging();
					this._NoTelepon = value;
					this.SendPropertyChanged("NoTelepon");
					this.OnNoTeleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal", DbType="Date")]
		public System.Nullable<System.DateTime> Tanggal
		{
			get
			{
				return this._Tanggal;
			}
			set
			{
				if ((this._Tanggal != value))
				{
					this.OnTanggalChanging(value);
					this.SendPropertyChanging();
					this._Tanggal = value;
					this.SendPropertyChanged("Tanggal");
					this.OnTanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat", DbType="VarChar(255)")]
		public string Alamat
		{
			get
			{
				return this._Alamat;
			}
			set
			{
				if ((this._Alamat != value))
				{
					this.OnAlamatChanging(value);
					this.SendPropertyChanging();
					this._Alamat = value;
					this.SendPropertyChanged("Alamat");
					this.OnAlamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keterangan", DbType="VarChar(255)")]
		public string Keterangan
		{
			get
			{
				return this._Keterangan;
			}
			set
			{
				if ((this._Keterangan != value))
				{
					this.OnKeteranganChanging(value);
					this.SendPropertyChanging();
					this._Keterangan = value;
					this.SendPropertyChanged("Keterangan");
					this.OnKeteranganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pemasok_pembelian", Storage="_pembelians", ThisKey="IdPemasok", OtherKey="IdPemasok")]
		public EntitySet<pembelian> pembelians
		{
			get
			{
				return this._pembelians;
			}
			set
			{
				this._pembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pemasok_produk", Storage="_produks", ThisKey="IdPemasok", OtherKey="IdPemasok")]
		public EntitySet<produk> produks
		{
			get
			{
				return this._produks;
			}
			set
			{
				this._produks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pembelians(pembelian entity)
		{
			this.SendPropertyChanging();
			entity.pemasok = this;
		}
		
		private void detach_pembelians(pembelian entity)
		{
			this.SendPropertyChanging();
			entity.pemasok = null;
		}
		
		private void attach_produks(produk entity)
		{
			this.SendPropertyChanging();
			entity.pemasok = this;
		}
		
		private void detach_produks(produk entity)
		{
			this.SendPropertyChanging();
			entity.pemasok = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pembelian")]
	public partial class pembelian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPembelian;
		
		private System.Nullable<System.DateTime> _Tanggal;
		
		private int _IdPemasok;
		
		private int _IdPengguna;
		
		private System.Nullable<decimal> _TotalHarga;
		
		private string _Catatan;
		
		private EntitySet<detailpembelian> _detailpembelians;
		
		private EntityRef<pemasok> _pemasok;
		
		private EntityRef<pengguna> _pengguna;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPembelianChanging(int value);
    partial void OnIdPembelianChanged();
    partial void OnTanggalChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggalChanged();
    partial void OnIdPemasokChanging(int value);
    partial void OnIdPemasokChanged();
    partial void OnIdPenggunaChanging(int value);
    partial void OnIdPenggunaChanged();
    partial void OnTotalHargaChanging(System.Nullable<decimal> value);
    partial void OnTotalHargaChanged();
    partial void OnCatatanChanging(string value);
    partial void OnCatatanChanged();
    #endregion
		
		public pembelian()
		{
			this._detailpembelians = new EntitySet<detailpembelian>(new Action<detailpembelian>(this.attach_detailpembelians), new Action<detailpembelian>(this.detach_detailpembelians));
			this._pemasok = default(EntityRef<pemasok>);
			this._pengguna = default(EntityRef<pengguna>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPembelian", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPembelian
		{
			get
			{
				return this._IdPembelian;
			}
			set
			{
				if ((this._IdPembelian != value))
				{
					this.OnIdPembelianChanging(value);
					this.SendPropertyChanging();
					this._IdPembelian = value;
					this.SendPropertyChanged("IdPembelian");
					this.OnIdPembelianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tanggal
		{
			get
			{
				return this._Tanggal;
			}
			set
			{
				if ((this._Tanggal != value))
				{
					this.OnTanggalChanging(value);
					this.SendPropertyChanging();
					this._Tanggal = value;
					this.SendPropertyChanged("Tanggal");
					this.OnTanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPemasok", DbType="Int NOT NULL")]
		public int IdPemasok
		{
			get
			{
				return this._IdPemasok;
			}
			set
			{
				if ((this._IdPemasok != value))
				{
					if (this._pemasok.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPemasokChanging(value);
					this.SendPropertyChanging();
					this._IdPemasok = value;
					this.SendPropertyChanged("IdPemasok");
					this.OnIdPemasokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPengguna", DbType="Int NOT NULL")]
		public int IdPengguna
		{
			get
			{
				return this._IdPengguna;
			}
			set
			{
				if ((this._IdPengguna != value))
				{
					if (this._pengguna.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPenggunaChanging(value);
					this.SendPropertyChanging();
					this._IdPengguna = value;
					this.SendPropertyChanged("IdPengguna");
					this.OnIdPenggunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalHarga", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TotalHarga
		{
			get
			{
				return this._TotalHarga;
			}
			set
			{
				if ((this._TotalHarga != value))
				{
					this.OnTotalHargaChanging(value);
					this.SendPropertyChanging();
					this._TotalHarga = value;
					this.SendPropertyChanged("TotalHarga");
					this.OnTotalHargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Catatan", DbType="VarChar(255)")]
		public string Catatan
		{
			get
			{
				return this._Catatan;
			}
			set
			{
				if ((this._Catatan != value))
				{
					this.OnCatatanChanging(value);
					this.SendPropertyChanging();
					this._Catatan = value;
					this.SendPropertyChanged("Catatan");
					this.OnCatatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pembelian_detailpembelian", Storage="_detailpembelians", ThisKey="IdPembelian", OtherKey="IdPembelian")]
		public EntitySet<detailpembelian> detailpembelians
		{
			get
			{
				return this._detailpembelians;
			}
			set
			{
				this._detailpembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pemasok_pembelian", Storage="_pemasok", ThisKey="IdPemasok", OtherKey="IdPemasok", IsForeignKey=true)]
		public pemasok pemasok
		{
			get
			{
				return this._pemasok.Entity;
			}
			set
			{
				pemasok previousValue = this._pemasok.Entity;
				if (((previousValue != value) 
							|| (this._pemasok.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pemasok.Entity = null;
						previousValue.pembelians.Remove(this);
					}
					this._pemasok.Entity = value;
					if ((value != null))
					{
						value.pembelians.Add(this);
						this._IdPemasok = value.IdPemasok;
					}
					else
					{
						this._IdPemasok = default(int);
					}
					this.SendPropertyChanged("pemasok");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pengguna_pembelian", Storage="_pengguna", ThisKey="IdPengguna", OtherKey="IdPengguna", IsForeignKey=true)]
		public pengguna pengguna
		{
			get
			{
				return this._pengguna.Entity;
			}
			set
			{
				pengguna previousValue = this._pengguna.Entity;
				if (((previousValue != value) 
							|| (this._pengguna.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pengguna.Entity = null;
						previousValue.pembelians.Remove(this);
					}
					this._pengguna.Entity = value;
					if ((value != null))
					{
						value.pembelians.Add(this);
						this._IdPengguna = value.IdPengguna;
					}
					else
					{
						this._IdPengguna = default(int);
					}
					this.SendPropertyChanged("pengguna");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailpembelians(detailpembelian entity)
		{
			this.SendPropertyChanging();
			entity.pembelian = this;
		}
		
		private void detach_detailpembelians(detailpembelian entity)
		{
			this.SendPropertyChanging();
			entity.pembelian = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pengguna")]
	public partial class pengguna : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPengguna;
		
		private string _NamaLengkap;
		
		private string _Username;
		
		private string _PasswordHash;
		
		private string _Role;
		
		private EntitySet<pembelian> _pembelians;
		
		private EntitySet<pesanan> _pesanans;
		
		private EntitySet<produk> _produks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPenggunaChanging(int value);
    partial void OnIdPenggunaChanged();
    partial void OnNamaLengkapChanging(string value);
    partial void OnNamaLengkapChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordHashChanging(string value);
    partial void OnPasswordHashChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    #endregion
		
		public pengguna()
		{
			this._pembelians = new EntitySet<pembelian>(new Action<pembelian>(this.attach_pembelians), new Action<pembelian>(this.detach_pembelians));
			this._pesanans = new EntitySet<pesanan>(new Action<pesanan>(this.attach_pesanans), new Action<pesanan>(this.detach_pesanans));
			this._produks = new EntitySet<produk>(new Action<produk>(this.attach_produks), new Action<produk>(this.detach_produks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPengguna", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPengguna
		{
			get
			{
				return this._IdPengguna;
			}
			set
			{
				if ((this._IdPengguna != value))
				{
					this.OnIdPenggunaChanging(value);
					this.SendPropertyChanging();
					this._IdPengguna = value;
					this.SendPropertyChanged("IdPengguna");
					this.OnIdPenggunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaLengkap", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NamaLengkap
		{
			get
			{
				return this._NamaLengkap;
			}
			set
			{
				if ((this._NamaLengkap != value))
				{
					this.OnNamaLengkapChanging(value);
					this.SendPropertyChanging();
					this._NamaLengkap = value;
					this.SendPropertyChanged("NamaLengkap");
					this.OnNamaLengkapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(20)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pengguna_pembelian", Storage="_pembelians", ThisKey="IdPengguna", OtherKey="IdPengguna")]
		public EntitySet<pembelian> pembelians
		{
			get
			{
				return this._pembelians;
			}
			set
			{
				this._pembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pengguna_pesanan", Storage="_pesanans", ThisKey="IdPengguna", OtherKey="IdPengguna")]
		public EntitySet<pesanan> pesanans
		{
			get
			{
				return this._pesanans;
			}
			set
			{
				this._pesanans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pengguna_produk", Storage="_produks", ThisKey="IdPengguna", OtherKey="IdPengguna")]
		public EntitySet<produk> produks
		{
			get
			{
				return this._produks;
			}
			set
			{
				this._produks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pembelians(pembelian entity)
		{
			this.SendPropertyChanging();
			entity.pengguna = this;
		}
		
		private void detach_pembelians(pembelian entity)
		{
			this.SendPropertyChanging();
			entity.pengguna = null;
		}
		
		private void attach_pesanans(pesanan entity)
		{
			this.SendPropertyChanging();
			entity.pengguna = this;
		}
		
		private void detach_pesanans(pesanan entity)
		{
			this.SendPropertyChanging();
			entity.pengguna = null;
		}
		
		private void attach_produks(produk entity)
		{
			this.SendPropertyChanging();
			entity.pengguna = this;
		}
		
		private void detach_produks(produk entity)
		{
			this.SendPropertyChanging();
			entity.pengguna = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pesanan")]
	public partial class pesanan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPesanan;
		
		private System.Nullable<System.DateTime> _Tanggal;
		
		private int _IdPelanggan;
		
		private int _IdPengguna;
		
		private System.Nullable<decimal> _TotalHarga;
		
		private string _StatusPengiriman;
		
		private string _Ekspedisi;
		
		private string _NoResi;
		
		private EntitySet<detailpesanan> _detailpesanans;
		
		private EntityRef<pelanggan> _pelanggan;
		
		private EntityRef<pengguna> _pengguna;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPesananChanging(int value);
    partial void OnIdPesananChanged();
    partial void OnTanggalChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggalChanged();
    partial void OnIdPelangganChanging(int value);
    partial void OnIdPelangganChanged();
    partial void OnIdPenggunaChanging(int value);
    partial void OnIdPenggunaChanged();
    partial void OnTotalHargaChanging(System.Nullable<decimal> value);
    partial void OnTotalHargaChanged();
    partial void OnStatusPengirimanChanging(string value);
    partial void OnStatusPengirimanChanged();
    partial void OnEkspedisiChanging(string value);
    partial void OnEkspedisiChanged();
    partial void OnNoResiChanging(string value);
    partial void OnNoResiChanged();
    #endregion
		
		public pesanan()
		{
			this._detailpesanans = new EntitySet<detailpesanan>(new Action<detailpesanan>(this.attach_detailpesanans), new Action<detailpesanan>(this.detach_detailpesanans));
			this._pelanggan = default(EntityRef<pelanggan>);
			this._pengguna = default(EntityRef<pengguna>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPesanan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPesanan
		{
			get
			{
				return this._IdPesanan;
			}
			set
			{
				if ((this._IdPesanan != value))
				{
					this.OnIdPesananChanging(value);
					this.SendPropertyChanging();
					this._IdPesanan = value;
					this.SendPropertyChanged("IdPesanan");
					this.OnIdPesananChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tanggal
		{
			get
			{
				return this._Tanggal;
			}
			set
			{
				if ((this._Tanggal != value))
				{
					this.OnTanggalChanging(value);
					this.SendPropertyChanging();
					this._Tanggal = value;
					this.SendPropertyChanged("Tanggal");
					this.OnTanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPelanggan", DbType="Int NOT NULL")]
		public int IdPelanggan
		{
			get
			{
				return this._IdPelanggan;
			}
			set
			{
				if ((this._IdPelanggan != value))
				{
					if (this._pelanggan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPelangganChanging(value);
					this.SendPropertyChanging();
					this._IdPelanggan = value;
					this.SendPropertyChanged("IdPelanggan");
					this.OnIdPelangganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPengguna", DbType="Int NOT NULL")]
		public int IdPengguna
		{
			get
			{
				return this._IdPengguna;
			}
			set
			{
				if ((this._IdPengguna != value))
				{
					if (this._pengguna.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPenggunaChanging(value);
					this.SendPropertyChanging();
					this._IdPengguna = value;
					this.SendPropertyChanged("IdPengguna");
					this.OnIdPenggunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalHarga", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TotalHarga
		{
			get
			{
				return this._TotalHarga;
			}
			set
			{
				if ((this._TotalHarga != value))
				{
					this.OnTotalHargaChanging(value);
					this.SendPropertyChanging();
					this._TotalHarga = value;
					this.SendPropertyChanged("TotalHarga");
					this.OnTotalHargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusPengiriman", DbType="VarChar(50)")]
		public string StatusPengiriman
		{
			get
			{
				return this._StatusPengiriman;
			}
			set
			{
				if ((this._StatusPengiriman != value))
				{
					this.OnStatusPengirimanChanging(value);
					this.SendPropertyChanging();
					this._StatusPengiriman = value;
					this.SendPropertyChanged("StatusPengiriman");
					this.OnStatusPengirimanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ekspedisi", DbType="VarChar(100)")]
		public string Ekspedisi
		{
			get
			{
				return this._Ekspedisi;
			}
			set
			{
				if ((this._Ekspedisi != value))
				{
					this.OnEkspedisiChanging(value);
					this.SendPropertyChanging();
					this._Ekspedisi = value;
					this.SendPropertyChanged("Ekspedisi");
					this.OnEkspedisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoResi", DbType="VarChar(100)")]
		public string NoResi
		{
			get
			{
				return this._NoResi;
			}
			set
			{
				if ((this._NoResi != value))
				{
					this.OnNoResiChanging(value);
					this.SendPropertyChanging();
					this._NoResi = value;
					this.SendPropertyChanged("NoResi");
					this.OnNoResiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pesanan_detailpesanan", Storage="_detailpesanans", ThisKey="IdPesanan", OtherKey="IdPesanan")]
		public EntitySet<detailpesanan> detailpesanans
		{
			get
			{
				return this._detailpesanans;
			}
			set
			{
				this._detailpesanans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pelanggan_pesanan", Storage="_pelanggan", ThisKey="IdPelanggan", OtherKey="IdPelanggan", IsForeignKey=true)]
		public pelanggan pelanggan
		{
			get
			{
				return this._pelanggan.Entity;
			}
			set
			{
				pelanggan previousValue = this._pelanggan.Entity;
				if (((previousValue != value) 
							|| (this._pelanggan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pelanggan.Entity = null;
						previousValue.pesanans.Remove(this);
					}
					this._pelanggan.Entity = value;
					if ((value != null))
					{
						value.pesanans.Add(this);
						this._IdPelanggan = value.IdPelanggan;
					}
					else
					{
						this._IdPelanggan = default(int);
					}
					this.SendPropertyChanged("pelanggan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pengguna_pesanan", Storage="_pengguna", ThisKey="IdPengguna", OtherKey="IdPengguna", IsForeignKey=true)]
		public pengguna pengguna
		{
			get
			{
				return this._pengguna.Entity;
			}
			set
			{
				pengguna previousValue = this._pengguna.Entity;
				if (((previousValue != value) 
							|| (this._pengguna.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pengguna.Entity = null;
						previousValue.pesanans.Remove(this);
					}
					this._pengguna.Entity = value;
					if ((value != null))
					{
						value.pesanans.Add(this);
						this._IdPengguna = value.IdPengguna;
					}
					else
					{
						this._IdPengguna = default(int);
					}
					this.SendPropertyChanged("pengguna");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailpesanans(detailpesanan entity)
		{
			this.SendPropertyChanging();
			entity.pesanan = this;
		}
		
		private void detach_detailpesanans(detailpesanan entity)
		{
			this.SendPropertyChanging();
			entity.pesanan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.produk")]
	public partial class produk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdProduk;
		
		private string _Nama;
		
		private int _IdKategori;
		
		private int _IdPemasok;
		
		private int _IdPengguna;
		
		private string _Deskripsi;
		
		private System.Nullable<decimal> _HargaDasar;
		
		private EntitySet<varianproduk> _varianproduks;
		
		private EntityRef<kategori> _kategori;
		
		private EntityRef<pemasok> _pemasok;
		
		private EntityRef<pengguna> _pengguna;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdProdukChanging(int value);
    partial void OnIdProdukChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnIdKategoriChanging(int value);
    partial void OnIdKategoriChanged();
    partial void OnIdPemasokChanging(int value);
    partial void OnIdPemasokChanged();
    partial void OnIdPenggunaChanging(int value);
    partial void OnIdPenggunaChanged();
    partial void OnDeskripsiChanging(string value);
    partial void OnDeskripsiChanged();
    partial void OnHargaDasarChanging(System.Nullable<decimal> value);
    partial void OnHargaDasarChanged();
    #endregion
		
		public produk()
		{
			this._varianproduks = new EntitySet<varianproduk>(new Action<varianproduk>(this.attach_varianproduks), new Action<varianproduk>(this.detach_varianproduks));
			this._kategori = default(EntityRef<kategori>);
			this._pemasok = default(EntityRef<pemasok>);
			this._pengguna = default(EntityRef<pengguna>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProduk", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdProduk
		{
			get
			{
				return this._IdProduk;
			}
			set
			{
				if ((this._IdProduk != value))
				{
					this.OnIdProdukChanging(value);
					this.SendPropertyChanging();
					this._IdProduk = value;
					this.SendPropertyChanged("IdProduk");
					this.OnIdProdukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKategori", DbType="Int NOT NULL")]
		public int IdKategori
		{
			get
			{
				return this._IdKategori;
			}
			set
			{
				if ((this._IdKategori != value))
				{
					if (this._kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdKategoriChanging(value);
					this.SendPropertyChanging();
					this._IdKategori = value;
					this.SendPropertyChanged("IdKategori");
					this.OnIdKategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPemasok", DbType="Int NOT NULL")]
		public int IdPemasok
		{
			get
			{
				return this._IdPemasok;
			}
			set
			{
				if ((this._IdPemasok != value))
				{
					if (this._pemasok.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPemasokChanging(value);
					this.SendPropertyChanging();
					this._IdPemasok = value;
					this.SendPropertyChanged("IdPemasok");
					this.OnIdPemasokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPengguna", DbType="Int NOT NULL")]
		public int IdPengguna
		{
			get
			{
				return this._IdPengguna;
			}
			set
			{
				if ((this._IdPengguna != value))
				{
					if (this._pengguna.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPenggunaChanging(value);
					this.SendPropertyChanging();
					this._IdPengguna = value;
					this.SendPropertyChanged("IdPengguna");
					this.OnIdPenggunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this.OnDeskripsiChanging(value);
					this.SendPropertyChanging();
					this._Deskripsi = value;
					this.SendPropertyChanged("Deskripsi");
					this.OnDeskripsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaDasar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> HargaDasar
		{
			get
			{
				return this._HargaDasar;
			}
			set
			{
				if ((this._HargaDasar != value))
				{
					this.OnHargaDasarChanging(value);
					this.SendPropertyChanging();
					this._HargaDasar = value;
					this.SendPropertyChanged("HargaDasar");
					this.OnHargaDasarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produk_varianproduk", Storage="_varianproduks", ThisKey="IdProduk", OtherKey="IdProduk")]
		public EntitySet<varianproduk> varianproduks
		{
			get
			{
				return this._varianproduks;
			}
			set
			{
				this._varianproduks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategori_produk", Storage="_kategori", ThisKey="IdKategori", OtherKey="IdKategori", IsForeignKey=true)]
		public kategori kategori
		{
			get
			{
				return this._kategori.Entity;
			}
			set
			{
				kategori previousValue = this._kategori.Entity;
				if (((previousValue != value) 
							|| (this._kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kategori.Entity = null;
						previousValue.produks.Remove(this);
					}
					this._kategori.Entity = value;
					if ((value != null))
					{
						value.produks.Add(this);
						this._IdKategori = value.IdKategori;
					}
					else
					{
						this._IdKategori = default(int);
					}
					this.SendPropertyChanged("kategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pemasok_produk", Storage="_pemasok", ThisKey="IdPemasok", OtherKey="IdPemasok", IsForeignKey=true)]
		public pemasok pemasok
		{
			get
			{
				return this._pemasok.Entity;
			}
			set
			{
				pemasok previousValue = this._pemasok.Entity;
				if (((previousValue != value) 
							|| (this._pemasok.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pemasok.Entity = null;
						previousValue.produks.Remove(this);
					}
					this._pemasok.Entity = value;
					if ((value != null))
					{
						value.produks.Add(this);
						this._IdPemasok = value.IdPemasok;
					}
					else
					{
						this._IdPemasok = default(int);
					}
					this.SendPropertyChanged("pemasok");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pengguna_produk", Storage="_pengguna", ThisKey="IdPengguna", OtherKey="IdPengguna", IsForeignKey=true)]
		public pengguna pengguna
		{
			get
			{
				return this._pengguna.Entity;
			}
			set
			{
				pengguna previousValue = this._pengguna.Entity;
				if (((previousValue != value) 
							|| (this._pengguna.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pengguna.Entity = null;
						previousValue.produks.Remove(this);
					}
					this._pengguna.Entity = value;
					if ((value != null))
					{
						value.produks.Add(this);
						this._IdPengguna = value.IdPengguna;
					}
					else
					{
						this._IdPengguna = default(int);
					}
					this.SendPropertyChanged("pengguna");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_varianproduks(varianproduk entity)
		{
			this.SendPropertyChanging();
			entity.produk = this;
		}
		
		private void detach_varianproduks(varianproduk entity)
		{
			this.SendPropertyChanging();
			entity.produk = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.varianproduk")]
	public partial class varianproduk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVarian;
		
		private int _IdProduk;
		
		private string _Ukuran;
		
		private string _Warna;
		
		private System.Nullable<int> _Jumlah;
		
		private System.Nullable<decimal> _HargaJual;
		
		private EntitySet<detailpembelian> _detailpembelians;
		
		private EntitySet<detailpesanan> _detailpesanans;
		
		private EntityRef<produk> _produk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVarianChanging(int value);
    partial void OnIdVarianChanged();
    partial void OnIdProdukChanging(int value);
    partial void OnIdProdukChanged();
    partial void OnUkuranChanging(string value);
    partial void OnUkuranChanged();
    partial void OnWarnaChanging(string value);
    partial void OnWarnaChanged();
    partial void OnJumlahChanging(System.Nullable<int> value);
    partial void OnJumlahChanged();
    partial void OnHargaJualChanging(System.Nullable<decimal> value);
    partial void OnHargaJualChanged();
    #endregion
		
		public varianproduk()
		{
			this._detailpembelians = new EntitySet<detailpembelian>(new Action<detailpembelian>(this.attach_detailpembelians), new Action<detailpembelian>(this.detach_detailpembelians));
			this._detailpesanans = new EntitySet<detailpesanan>(new Action<detailpesanan>(this.attach_detailpesanans), new Action<detailpesanan>(this.detach_detailpesanans));
			this._produk = default(EntityRef<produk>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVarian", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVarian
		{
			get
			{
				return this._IdVarian;
			}
			set
			{
				if ((this._IdVarian != value))
				{
					this.OnIdVarianChanging(value);
					this.SendPropertyChanging();
					this._IdVarian = value;
					this.SendPropertyChanged("IdVarian");
					this.OnIdVarianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProduk", DbType="Int NOT NULL")]
		public int IdProduk
		{
			get
			{
				return this._IdProduk;
			}
			set
			{
				if ((this._IdProduk != value))
				{
					if (this._produk.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProdukChanging(value);
					this.SendPropertyChanging();
					this._IdProduk = value;
					this.SendPropertyChanged("IdProduk");
					this.OnIdProdukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ukuran", DbType="VarChar(10)")]
		public string Ukuran
		{
			get
			{
				return this._Ukuran;
			}
			set
			{
				if ((this._Ukuran != value))
				{
					this.OnUkuranChanging(value);
					this.SendPropertyChanging();
					this._Ukuran = value;
					this.SendPropertyChanged("Ukuran");
					this.OnUkuranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Warna", DbType="VarChar(30)")]
		public string Warna
		{
			get
			{
				return this._Warna;
			}
			set
			{
				if ((this._Warna != value))
				{
					this.OnWarnaChanging(value);
					this.SendPropertyChanging();
					this._Warna = value;
					this.SendPropertyChanged("Warna");
					this.OnWarnaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah", DbType="Int")]
		public System.Nullable<int> Jumlah
		{
			get
			{
				return this._Jumlah;
			}
			set
			{
				if ((this._Jumlah != value))
				{
					this.OnJumlahChanging(value);
					this.SendPropertyChanging();
					this._Jumlah = value;
					this.SendPropertyChanged("Jumlah");
					this.OnJumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HargaJual", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> HargaJual
		{
			get
			{
				return this._HargaJual;
			}
			set
			{
				if ((this._HargaJual != value))
				{
					this.OnHargaJualChanging(value);
					this.SendPropertyChanging();
					this._HargaJual = value;
					this.SendPropertyChanged("HargaJual");
					this.OnHargaJualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="varianproduk_detailpembelian", Storage="_detailpembelians", ThisKey="IdVarian", OtherKey="IdVarian")]
		public EntitySet<detailpembelian> detailpembelians
		{
			get
			{
				return this._detailpembelians;
			}
			set
			{
				this._detailpembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="varianproduk_detailpesanan", Storage="_detailpesanans", ThisKey="IdVarian", OtherKey="IdVarian")]
		public EntitySet<detailpesanan> detailpesanans
		{
			get
			{
				return this._detailpesanans;
			}
			set
			{
				this._detailpesanans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produk_varianproduk", Storage="_produk", ThisKey="IdProduk", OtherKey="IdProduk", IsForeignKey=true)]
		public produk produk
		{
			get
			{
				return this._produk.Entity;
			}
			set
			{
				produk previousValue = this._produk.Entity;
				if (((previousValue != value) 
							|| (this._produk.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._produk.Entity = null;
						previousValue.varianproduks.Remove(this);
					}
					this._produk.Entity = value;
					if ((value != null))
					{
						value.varianproduks.Add(this);
						this._IdProduk = value.IdProduk;
					}
					else
					{
						this._IdProduk = default(int);
					}
					this.SendPropertyChanged("produk");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detailpembelians(detailpembelian entity)
		{
			this.SendPropertyChanging();
			entity.varianproduk = this;
		}
		
		private void detach_detailpembelians(detailpembelian entity)
		{
			this.SendPropertyChanging();
			entity.varianproduk = null;
		}
		
		private void attach_detailpesanans(detailpesanan entity)
		{
			this.SendPropertyChanging();
			entity.varianproduk = this;
		}
		
		private void detach_detailpesanans(detailpesanan entity)
		{
			this.SendPropertyChanging();
			entity.varianproduk = null;
		}
	}
}
#pragma warning restore 1591
